#
# Message in A bottle Docker Compose file
#

version: "3.6"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # this is only for development purpose
      - "5342:5342"
    env_file:
      - env_file

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  worker:
    image: "worker:lasest"
    build:
      context: . 
      dockerfile: DockerfileCelery
    command: [celery, -A, mib.background, worker, -l, INFO]
    depends_on:
      - redis
      - mib_messages
    env_file:
      - env_file
  scheduler:
    image: "scheduler:lesest"
      build:
        contentx: .
        dockerfile: DockerfileCelery
    command: [celery, -A, mib.background, beat , -l, INFO]
    depends_on:
      - redis
      - mib_messages
    env_file:
      - env_file

  mib_messages:
    <<: &mib_messages
      # Building the image
      image: "mib-messages:latest"
      build:
        context: .
        dockerfile: Dockerfile 

    ports:
     - "5000:5000"
    env_file:
      - env_file
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - migrations
      - redis