#
# Message in A bottle Docker Compose file
#
version: "3.6"

services:
  redis:
    image: "redis:alpine"
    ports:  
      - "6379:6379"
  worker:
    image: "worker:lasest"
    build:
      context: .
      dockerfile: DockerfileCelery
    command: [celery, -A, mib.background, worker, -l, INFO]
    depends_on:
      - redis
    env_file:
      - env_file
  scheduler:
    image: "scheduler:lesest"
    build:
      context: .
      dockerfile: DockerfileCelery
    command: [celery, -A, mib.background, beat , -l, INFO]
    depends_on:
      - redis
    env_file:
      - env_file

  mib_periodic_task:
    <<: &mib_messages
      # Building the image
      image: "mib_periodic_task:latest"
      build:
        context: .
        dockerfile: Dockerfile 
    ports:
     - "5000:5000"
    env_file:
      - env_file
    depends_on:
      - redis
      - scheduler
      - worker